### ISSUE TITLE
how to implement pagination?

### ISSUE THREAD

**Issue by luckypoem** [johannhof/johannhof.github.io#2]
hi.

i setup a blog as per ur repo: http://jh.bright.biz.st ,but how to implement pagination?

tks

**Comment by johannhof** [comment]
Hi, Cobalt doesn't support pagination yet. Feel free to make an issue at https://github.com/cobalt-org/cobalt.rs!

Thanks!

**Comment by johannhof** [comment]
Also, while it's awesome that you adapted my website style, I'd appreciate if you could delete my personal content from your page :heart:
