### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by stensonowen** [johannhof/johannhof.github.io#3]
[Omitting a license from a github repo means all rights are reserved.](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license). Because you are a contributor to a [Cobalt](https://github.com/cobalt-org/cobalt.rs), which [links to your project's source](https://github.com/cobalt-org/cobalt.rs/blob/master/README.md#examples) as an example implementation, I assume you are open to new users studying your code and modifying it to implement their own sites. Currently this is prohibited, but an open source license would grant permission to others to do this.

The [GPL](http://choosealicense.com/licenses/gpl-3.0/) is a personal favorite; the [MIT license](http://choosealicense.com/licenses/mit/) is also quite common and what Cobalt uses. [choosealicense.com](http://choosealicense.com/) is a helpful resource if you aren't familiar with may licenses.

**Comment by johannhof** [comment]
Yeah, I should look that up. Thanks for notifying me!
